# Generated by Django 5.2.4 on 2025-07-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0002_remove_financial_type_if_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='True when item is checked out/archived'),
        ),
    ]
