# Generated by Django 5.2.4 on 2025-07-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_requests', '0003_request_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_archived',
        ),
    ]
