# Generated by Django 5.2.4 on 2025-08-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_create_usage_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipmentusagelog',
            new_name='schedule_eq_equipme_2088a1_idx',
            old_name='schedule_eq_equip_check_in_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentusagelog',
            new_name='schedule_eq_user_id_e03600_idx',
            old_name='schedule_eq_user_check_in_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentusagelog',
            new_name='schedule_eq_is_acti_880401_idx',
            old_name='schedule_eq_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentusagelog',
            new_name='schedule_eq_check_i_811aa5_idx',
            old_name='schedule_eq_check_in_time_idx',
        ),
        migrations.RenameIndex(
            model_name='waitingqueueentry',
            new_name='schedule_wa_equipme_156a2c_idx',
            old_name='schedule_wq_equip_status_idx',
        ),
        migrations.RenameIndex(
            model_name='waitingqueueentry',
            new_name='schedule_wa_user_id_5afd91_idx',
            old_name='schedule_wq_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='waitingqueueentry',
            new_name='schedule_wa_expires_e3a566_idx',
            old_name='schedule_wq_expires_at_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(help_text='Booked equipment', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.equipment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.OneToOneField(help_text='Associated event', on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='schedule.event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Booking notes', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', help_text='Booking status', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(help_text='Booking user', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='waiting_list',
            field=models.ManyToManyField(blank=True, help_text='Users in waiting list', related_name='waiting_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, help_text='Equipment description', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_bookable',
            field=models.BooleanField(default=True, help_text='Whether equipment can be booked'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, help_text='Equipment location', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Equipment name, e.g., Microscope, BSC', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='requires_qr_checkin',
            field=models.BooleanField(default=False, help_text='Whether QR code check-in is required'),
        ),
    ]
