# Generated by Django 5.2.4 on 2025-08-08 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedule', '0004_calendarsyncrecord_meetingconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarsyncrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='schedule_ca_content_49a524_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsyncrecord',
            index=models.Index(fields=['google_event_id'], name='schedule_ca_google__175f78_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsyncrecord',
            index=models.Index(fields=['sync_status'], name='schedule_ca_sync_st_a331b7_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['equipment', 'check_in_time'], name='schedule_eq_equipme_2088a1_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['user', 'check_in_time'], name='schedule_eq_user_id_e03600_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['is_active'], name='schedule_eq_is_acti_880401_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentusagelog',
            index=models.Index(fields=['check_in_time'], name='schedule_eq_check_i_811aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='periodictaskinstance',
            index=models.Index(fields=['scheduled_period'], name='schedule_pe_schedul_a85a15_idx'),
        ),
        migrations.AddIndex(
            model_name='periodictaskinstance',
            index=models.Index(fields=['status'], name='schedule_pe_status_60173e_idx'),
        ),
        migrations.AddIndex(
            model_name='periodictaskinstance',
            index=models.Index(fields=['execution_start_date'], name='schedule_pe_executi_6debbe_idx'),
        ),
        migrations.AddIndex(
            model_name='periodictaskinstance',
            index=models.Index(fields=['execution_end_date'], name='schedule_pe_executi_7f65b5_idx'),
        ),
        migrations.AddIndex(
            model_name='waitingqueueentry',
            index=models.Index(fields=['equipment', 'status'], name='schedule_wa_equipme_156a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='waitingqueueentry',
            index=models.Index(fields=['user', 'status'], name='schedule_wa_user_id_5afd91_idx'),
        ),
        migrations.AddIndex(
            model_name='waitingqueueentry',
            index=models.Index(fields=['expires_at'], name='schedule_wa_expires_e3a566_idx'),
        ),
    ]
