# Generated by Django 5.2.4 on 2025-08-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '9999_remove_qr_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentusagelog',
            name='qr_scan_method',
            field=models.CharField(choices=[('mobile_camera', 'Mobile Camera'), ('desktop_webcam', 'Desktop Webcam'), ('manual_entry', 'Manual Entry')], default='manual_entry', help_text='Method used to scan QR code (legacy field)', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, help_text='Equipment location', max_length=255, null=True),
        ),
    ]
