# Generated by Django 5.2.4 on 2025-07-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="funding_agency",
        ),
    ]
