# Generated by Django 5.2.4 on 2025-07-22 17:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="annual_budgets",
            field=models.JSONField(
                default=dict,
                help_text='Annual budget allocations: {"2024": 50000.00, "2025": 55000.00, ...}',
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="current_year",
            field=models.IntegerField(
                default=1,
                help_text="Current year of the multi-year grant",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="funding_agency",
            field=models.CharField(
                choices=[
                    ("cihr", "Canadian Institutes of Health Research (CIHR)"),
                    (
                        "nserc",
                        "Natural Sciences and Engineering Research Council (NSERC)",
                    ),
                    (
                        "sshrc",
                        "Social Sciences and Humanities Research Council (SSHRC)",
                    ),
                    ("other", "Other Funding Source"),
                ],
                default="other",
                help_text="Canadian Tri-Agency or other funding source",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="grant_duration_years",
            field=models.IntegerField(
                default=1,
                help_text="Total duration of the grant in years",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="fundingreport",
            name="fiscal_year",
            field=models.IntegerField(
                blank=True,
                help_text="Fiscal year for this report (auto-calculated)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fundingreport",
            name="is_tri_agency_compliant",
            field=models.BooleanField(
                default=False,
                help_text="Meets Canadian Tri-Agency reporting requirements",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cost_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Research Cost"),
                    ("indirect", "Indirect Cost (Administrative)"),
                ],
                default="direct",
                help_text="Classify as direct research cost or indirect administrative cost",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="expense_category",
            field=models.CharField(
                choices=[
                    ("personnel", "Personnel Salaries & Benefits"),
                    ("equipment", "Equipment"),
                    ("supplies", "Supplies & Materials"),
                    ("travel", "Travel & Conference"),
                    ("services", "Professional Services"),
                    ("facilities", "Facilities & Overhead"),
                    ("other", "Other Direct Costs"),
                ],
                default="supplies",
                help_text="Expense category for TAGFA reporting requirements",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="fiscal_year",
            field=models.IntegerField(
                blank=True,
                help_text="Fiscal year for this transaction (auto-calculated)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="vendor",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="fundingreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly Report"),
                    ("quarterly", "Quarterly Report"),
                    ("annual", "Annual Report"),
                    ("custom", "Custom Report"),
                    ("form300", "Form 300 - Grants in Aid of Research Statement"),
                    ("tri_agency_annual", "Tri-Agency Annual Financial Report"),
                    ("audit_trail", "Audit Trail Report (7-year compliance)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fundingreport",
            name="summary_data",
            field=models.JSONField(
                default=dict,
                help_text="Summary data including direct/indirect costs, category breakdowns, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("adjustment", "Budget Adjustment"),
                    ("transfer", "Fund Transfer"),
                    ("refund", "Refund"),
                    ("carryover", "Carry-over from Previous Year"),
                ],
                default="purchase",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FundCarryOver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_fiscal_year",
                    models.IntegerField(
                        help_text="Fiscal year the funds are being carried over from"
                    ),
                ),
                (
                    "to_fiscal_year",
                    models.IntegerField(
                        help_text="Fiscal year the funds are being carried over to"
                    ),
                ),
                (
                    "carryover_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount being carried over",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "original_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original budget for the from_fiscal_year",
                        max_digits=12,
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount spent in the from_fiscal_year",
                        max_digits=12,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this carry-over has been approved by administrator",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the carry-over transaction has been created",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_carryovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carryovers",
                        to="funding.fund",
                    ),
                ),
            ],
            options={
                "ordering": ["-from_fiscal_year", "-created_at"],
                "unique_together": {("fund", "from_fiscal_year", "to_fiscal_year")},
            },
        ),
    ]
