# Generated by Django 5.2.4 on 2025-07-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding", "0002_remove_fund_funding_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="funding_agency",
            field=models.IntegerField(
                choices=[
                    (1, "Canadian Institutes of Health Research (CIHR)"),
                    (2, "Natural Sciences and Engineering Research Council (NSERC)"),
                    (3, "Social Sciences and Humanities Research Council (SSHRC)"),
                    (4, "Other Funding Source"),
                ],
                default=4,
                help_text="Canadian Tri-Agency or other funding source",
            ),
        ),
    ]
