# Generated by Django 5.2.4 on 2025-07-25 07:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_budgetcategory_currency_fundingagency_costcenter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(help_text='Name of the employee', max_length=200)),
                ('expense_type', models.CharField(choices=[('salary', 'Salary'), ('benefits', 'Benefits'), ('stipend', 'Stipend'), ('bonus', 'Bonus'), ('training', 'Training'), ('travel', 'Travel')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(help_text='Date of the expense')),
                ('description', models.TextField(blank=True, help_text='Additional details about the expense')),
                ('reference_number', models.CharField(blank=True, help_text='Reference or invoice number', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_personnel_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_personnel_expenses', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_expenses', to='funding.fund')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
