# Generated by Django 5.2.4 on 2025-07-25 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_personnelexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelexpense',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='The employee for this expense', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnel_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
