# Generated by Django 5.2.4 on 2025-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_personnelexpense_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelexpense',
            name='employee_name',
            field=models.CharField(blank=True, help_text='Name of the employee', max_length=200),
        ),
    ]
