# Generated by Django 5.2.4 on 2025-07-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiration_alert_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before expiration to trigger alert'),
        ),
        migrations.AddField(
            model_name='item',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Expiration date of the item', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_used_date',
            field=models.DateField(blank=True, help_text='Last time this item was used', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Batch/lot number for tracking', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date when the item was received/opened', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='storage_conditions',
            field=models.TextField(blank=True, help_text='Additional storage requirements'),
        ),
        migrations.AddField(
            model_name='item',
            name='storage_temperature',
            field=models.CharField(blank=True, help_text='Required storage temperature (e.g., -80°C, 4°C, RT)', max_length=50),
        ),
    ]
