# Generated by Django 5.2.4 on 2025-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_expiration_alert_days_item_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="fund_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the fund used to purchase this item",
                null=True,
            ),
        ),
    ]
