# Generated by Django 5.2.4 on 2025-07-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_fund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='financial_type',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Supplies', 'Supplies')], default='Supplies', help_text='Financial classification for reporting (Equipment or Supplies)', max_length=20),
        ),
    ]
