# Generated by Django 5.2.4 on 2025-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_fund_id'),
    ]

    operations = [
        # This migration syncs the model with existing database schema
        # The financial_type field was added by another branch but we need to 
        # acknowledge it in our migration history
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL - field already exists in database
            reverse_sql="SELECT 1;"
        ),
    ]
