# Generated by Django 5.2.4 on 2026-03-07 19:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_location_metadata(apps, schema_editor):
    Location = apps.get_model('items', 'Location')
    for location in Location.objects.all():
        has_children = Location.objects.filter(parent_id=location.id).exists()
        if location.parent_id is None:
            location.location_type = 'area'
            location.is_leaf = False
        elif has_children:
            location.location_type = 'container'
            location.is_leaf = False
        else:
            location.location_type = 'slot'
            location.is_leaf = True
        location.save(update_fields=['location_type', 'is_leaf'])


def forward_fill_allocations(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    ItemLocationAllocation = apps.get_model('items', 'ItemLocationAllocation')
    Location = apps.get_model('items', 'Location')

    for item in Item.objects.exclude(location_id__isnull=True):
        if item.quantity is None or item.quantity <= 0:
            continue
        if ItemLocationAllocation.objects.filter(item_id=item.id).exists():
            continue

        location = Location.objects.get(id=item.location_id)
        ItemLocationAllocation.objects.create(
            item_id=item.id,
            location_id=location.id,
            quantity=item.quantity,
            note='Auto-migrated from legacy item.location.',
            sort_order=0,
        )


def reverse_fill_allocations(apps, schema_editor):
    ItemLocationAllocation = apps.get_model('items', 'ItemLocationAllocation')
    ItemLocationAllocation.objects.filter(note='Auto-migrated from legacy item.location.', sort_order=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_add_barcode_field_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['parent__id', 'sort_order', 'name', 'id']},
        ),
        migrations.AddField(
            model_name='location',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='Alternative names used for this location.'),
        ),
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, help_text='Optional stable code for imports and integrations.', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_leaf',
            field=models.BooleanField(default=True, help_text='Whether this location is a final storable slot.'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('area', 'Area'), ('storage_group', 'Storage Group'), ('container', 'Container'), ('slot', 'Slot')], default='slot', max_length=32),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional operational notes for this location.'),
        ),
        migrations.AddField(
            model_name='location',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='items_location_unique_name_per_parent'),
        ),
        migrations.AddField(
            model_name='itemlocationallocation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_allocations', to='items.item'),
        ),
        migrations.AddField(
            model_name='itemlocationallocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_allocations', to='items.location'),
        ),
        migrations.AddConstraint(
            model_name='itemlocationallocation',
            constraint=models.UniqueConstraint(fields=('item', 'location'), name='items_itemallocation_unique_item_location'),
        ),
        migrations.AddConstraint(
            model_name='itemlocationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='items_itemallocation_quantity_positive'),
        ),
        migrations.RunPython(backfill_location_metadata, migrations.RunPython.noop),
        migrations.RunPython(forward_fill_allocations, reverse_fill_allocations),
    ]
