# Generated by Django 5.2.4 on 2026-03-09 20:05

from django.db import migrations, models


def seed_tracking_defaults(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    ItemType = apps.get_model('items', 'ItemType')

    pack_keywords = ('consumable', 'media', 'tissue culture', 'general supply', 'plasticware')
    unlabeled_instance_keywords = ('antibody', 'drug', 'inhibitor', 'small molecule')

    for item_type in ItemType.objects.all():
        name = (item_type.name or '').strip().lower()
        if any(keyword in name for keyword in pack_keywords):
            item_type.tracking_mode = 'pack_managed'
            item_type.label_mode = 'none'
        elif any(keyword in name for keyword in unlabeled_instance_keywords):
            item_type.tracking_mode = 'instance_tracked'
            item_type.label_mode = 'none'
        else:
            item_type.tracking_mode = 'instance_tracked'
            item_type.label_mode = 'item_barcode'
        item_type.save(update_fields=['tracking_mode', 'label_mode'])

    for item in Item.objects.exclude(barcode__isnull=True).exclude(barcode=''):
        item.label_mode = 'item_barcode'
        item.save(update_fields=['label_mode'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_itemlocationallocation_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_mode',
            field=models.CharField(blank=True, choices=[('none', 'No physical barcode'), ('item_barcode', 'Barcode on item')], help_text='Optional per-item override for barcode label handling.', max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='tracking_mode',
            field=models.CharField(blank=True, choices=[('pack_managed', 'Pack-managed'), ('instance_tracked', 'Instance-tracked')], help_text='Optional per-item override for how this stock is tracked.', max_length=32),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='label_mode',
            field=models.CharField(choices=[('none', 'No physical barcode'), ('item_barcode', 'Barcode on item')], default='item_barcode', help_text='Defines whether physical barcode labels should be generated for this type.', max_length=32),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='tracking_mode',
            field=models.CharField(choices=[('pack_managed', 'Pack-managed'), ('instance_tracked', 'Instance-tracked')], default='instance_tracked', help_text='Controls whether this type is managed as pack counts or as discrete trackable instances.', max_length=32),
        ),
        migrations.RunPython(seed_tracking_defaults, noop_reverse),
    ]
