# Generated by Django 5.2.4 on 2025-07-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_alerts', models.CharField(choices=[('web', 'Web Only'), ('email', 'Email Only'), ('both', 'Web and Email'), ('none', 'Disabled')], default='web', help_text='How to receive inventory alerts (expired/low stock)', max_length=10)),
                ('request_updates', models.CharField(choices=[('web', 'Web Only'), ('email', 'Email Only'), ('both', 'Web and Email'), ('none', 'Disabled')], default='web', help_text='How to receive request status updates', max_length=10)),
                ('system_notifications', models.CharField(choices=[('web', 'Web Only'), ('email', 'Email Only'), ('both', 'Web and Email'), ('none', 'Disabled')], default='web', help_text='How to receive system notifications', max_length=10)),
                ('funding_alerts', models.CharField(choices=[('web', 'Web Only'), ('email', 'Email Only'), ('both', 'Web and Email'), ('none', 'Disabled')], default='web', help_text='How to receive funding/budget alerts', max_length=10)),
                ('enable_daily_digest', models.BooleanField(default=False, help_text='Send daily digest of notifications via email')),
                ('enable_weekly_digest', models.BooleanField(default=False, help_text='Send weekly digest of notifications via email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short notification title', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('inventory_alert', 'Inventory Alert'), ('request_update', 'Request Update'), ('system', 'System')], default='info', help_text='Type of notification', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the notification', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('is_dismissed', models.BooleanField(default=False, help_text='Whether the notification has been dismissed')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification should expire (optional)', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who should receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type', 'priority'], name='notificatio_notific_b9c0e7_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx')],
            },
        ),
    ]
