# Generated by Django 5.2.4 on 2025-08-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='task_assignments',
            field=models.CharField(choices=[('web', 'Web Only'), ('email', 'Email Only'), ('both', 'Web and Email'), ('none', 'Disabled')], default='both', help_text='How to receive task assignment notifications', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='task_reminders',
            field=models.CharField(choices=[('web', 'Web Only'), ('email', 'Email Only'), ('both', 'Web and Email'), ('none', 'Disabled')], default='both', help_text='How to receive task deadline reminders', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='task_swaps',
            field=models.CharField(choices=[('web', 'Web Only'), ('email', 'Email Only'), ('both', 'Web and Email'), ('none', 'Disabled')], default='web', help_text='How to receive task swap request notifications', max_length=10),
        ),
    ]
