# Generated by Django 5.2.4 on 2025-07-21 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=10)),
                ('catalog_number', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_size', models.CharField(blank=True, help_text='e.g., 100 uL, 500 g', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
