# Generated by Django 5.2.4 on 2025-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_requesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='fund_id',
            field=models.IntegerField(blank=True, help_text='ID of the fund used for this request', null=True),
        ),
    ]
