# Generated by Django 5.2.4 on 2025-07-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_fund_id'),
        ('requests', '0003_request_fund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemtype'),
        ),
    ]
