# Generated by Django 5.2.4 on 2025-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_request_item_type'),
    ]

    operations = [
        # Check if columns exist before adding them
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'requests_request' AND column_name = 'financial_type'
                ) THEN
                    ALTER TABLE requests_request ADD COLUMN financial_type VARCHAR(20) DEFAULT 'Supplies';
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE requests_request DROP COLUMN IF EXISTS financial_type;"
        ),
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'requests_request' AND column_name = 'barcode'
                ) THEN
                    ALTER TABLE requests_request ADD COLUMN barcode VARCHAR(50) UNIQUE;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE requests_request DROP COLUMN IF EXISTS barcode;"
        ),
    ]
