# Generated by Django 5.2.4 on 2025-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_request_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='financial_type',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Supplies', 'Supplies')], default='Supplies', help_text='Financial classification for reporting (Equipment or Supplies)', max_length=20),
        ),
    ]
