# Generated by Django 5.2.4 on 2025-07-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_request_financial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='barcode',
            field=models.CharField(blank=True, help_text='Unique barcode for this request', max_length=50, null=True, unique=True),
        ),
    ]
